source "https://rubygems.org"

ruby "3.3.2"

# Rails本体
gem "rails", "~> 7.1.3", ">= 7.1.3.4"

# データベースとWebサーバー
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"

# 認証と暗号化
gem "bcrypt", "~> 3.1.7"
gem "devise"
gem "devise-jwt"

# API用のユーティリティ
gem "rack-cors"

# Redisとセッション管理
gem "redis", ">= 4.0.1"
gem "kredis"

# キャッシュとデバッグの高速化
gem "bootsnap", require: false

# タイムゾーン設定 (Windows環境でのみ必要)
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end

group :development do
  gem "spring"
end